# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-26 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsale',
            name='total_price',
        ),
    ]
